### ISSUE TITLE
Report: error occurred when executing command "wordmove" on VCCW

### ISSUE THREAD

**Issue by DriftwoodJP** [vccw-team/vccw#258]
`vagrant ssh` to VCCW v3.3.1

```
vagrant@foo:/vagrant$ wordmove pull --all
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json/pure (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/json.rb:61:in `rescue in <module:JSON>'
	from /usr/lib/ruby/2.3.0/json.rb:58:in `<module:JSON>'
	from /usr/lib/ruby/2.3.0/json.rb:55:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vagrant/.gem/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext/object/json.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vagrant/.gem/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vagrant/.gem/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /home/vagrant/.gem/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext.rb:1:in `each'
	from /home/vagrant/.gem/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vagrant/.gem/ruby/2.3.0/gems/wordmove-2.0.0/lib/wordmove.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vagrant/.gem/ruby/2.3.0/gems/wordmove-2.0.0/exe/wordmove:5:in `<top (required)>'
	from /home/vagrant/.gem/ruby/2.3.0/bin/wordmove:23:in `load'
	from /home/vagrant/.gem/ruby/2.3.0/bin/wordmove:23:in `<main>'
```

It requires "json/pure".
`gem install json_pure`, resolving the problem.

```
vagrant@foo:/vagrant$ sudo gem install json_pure
```

Operating System: macOS 10.12.5
Vagrant Version: 1.9.5
Virtual Box Version: 5.1.22 r115126

**Comment by miya0001** [comment]
Hmm, I couldn't reproduce the problem.
The `wordmove` command works fine without `json_pure` for me.

If you have a problem again, please try `vagrant provision` and report to us.

Thanks!
