### ISSUE TITLE
vagrant reload --provision fails

### ISSUE THREAD

**Issue by testower** [vccw-team/vccw#63]
```
==> default: Running chef-solo...
==> default: [2015-02-15T11:16:41+00:00] INFO: Forking chef instance to converge...
==> default: [2015-02-15T11:16:41+00:00] WARN:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> default: encrypted, but chef is not able to detect forged replies or man in the middle
==> default: attacks.
==> default:
==> default: To fix this issue add an entry like this to your configuration file:
==> default:
==> default: ```
==> default:   # Verify all HTTPS connections (recommended)
==> default:   ssl_verify_mode :verify_peer
==> default:
==> default:   # OR, Verify only connections to chef-server
==> default:   verify_api_cert true
==> default: ```
==> default:
==> default: To check your SSL configuration, or troubleshoot errors, you can use the
==> default: `knife ssl check` command like so:
==> default:
==> default: ```
==> default:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> default: ```
==> default:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: [2015-02-15T11:16:41+00:00] INFO: *** Chef 11.16.4 ***
==> default: [2015-02-15T11:16:41+00:00] INFO: Chef-client pid: 19626
==> default: [2015-02-15T11:16:42+00:00] INFO: Setting the run_list to ["recipe[yum::remi]", "recipe[iptables]", "recipe[apache2]", "recipe[apache2::mod_php5]", "recipe[apache2::mod_ssl]", "recipe[mysql::server]", "recipe[mysql::ruby]", "recipe[php::package]", "recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> default: [2015-02-15T11:16:42+00:00] INFO: Run List is [recipe[yum::remi], recipe[iptables], recipe[apache2], recipe[apache2::mod_php5], recipe[apache2::mod_ssl], recipe[mysql::server], recipe[mysql::ruby], recipe[php::package], recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> default: [2015-02-15T11:16:42+00:00] INFO: Run List expands to [yum::remi, iptables, apache2, apache2::mod_php5, apache2::mod_ssl, mysql::server, mysql::ruby, php::package, wpcli, wpcli::install, vccw]
==> default: [2015-02-15T11:16:42+00:00] INFO: Starting Chef Run for lsb.vagrant
==> default: [2015-02-15T11:16:42+00:00] INFO: Running start handlers
==> default: [2015-02-15T11:16:42+00:00] INFO: Start handlers complete.
==> default: [2015-02-15T11:16:42+00:00] ERROR: Running exception handlers
==> default: [2015-02-15T11:16:42+00:00] ERROR: Exception handlers complete
==> default: [2015-02-15T11:16:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-02-15T11:16:42+00:00] ERROR: Cookbook yum not found. If you're loading yum from another cookbook, make sure you configure the dependency in your metadata
==> default: [2015-02-15T11:16:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Output from /var/chef/cache/chef-stacktrace.out:

```
Generated at 2015-02-15 11:16:42 +0000
Chef::Exceptions::CookbookNotFound: Cookbook yum not found. If you're loading yum from another cookbook, make sure you configure the dependency in your metadata
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/cookbook/cookbook_collection.rb:38:in `block in initialize'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/mash.rb:77:in `yield'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/mash.rb:77:in `default'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/mash.rb:77:in `default'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:277:in `[]'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:277:in `each_cookbook_dep'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:255:in `add_cookbook_with_deps'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:88:in `block in cookbook_order'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:86:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:86:in `cookbook_order'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/run_context.rb:89:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:265:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:429:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/solo.rb:226:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'
```

**Comment by miya0001** [comment]
Try --provision after reload vagrant once.
Or please upgrade vagrant and virtualbox to the latest.

**Comment by bobhattori** [comment]
same issue here
after I got same error above
I've added 
chef.custom_config_path = "Vagrantfile.chef"
to my vagrantfile
then create Vagrantfile.chef and write
Chef::Config.ssl_verify_mode = :verify_peer
in it.
then I got these errors now

Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: [2015-02-24T04:48:34+00:00] INFO: Forking chef instance to converge...
==> default: [2015-02-24T04:48:34+00:00] INFO: *** Chef 11.16.4 ***
==> default: [2015-02-24T04:48:34+00:00] INFO: Chef-client pid: 18055
==> default: [2015-02-24T04:48:51+00:00] INFO: Setting the run_list to ["recipe[yum::remi]", "recipe[iptables]", "recipe[apache2]", "recipe[apache2::mod_php5]", "recipe[apache2::mod_ssl]", "recipe[mysql::server]", "recipe[mysql::ruby]", "recipe[php::package]", "recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> default: [2015-02-24T04:48:51+00:00] INFO: Run List is [recipe[yum::remi], recipe[iptables], recipe[apache2], recipe[apache2::mod_php5], recipe[apache2::mod_ssl], recipe[mysql::server], recipe[mysql::ruby], recipe[php::package], recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> default: [2015-02-24T04:48:51+00:00] INFO: Run List expands to [yum::remi, iptables, apache2, apache2::mod_php5, apache2::mod_ssl, mysql::server, mysql::ruby, php::package, wpcli, wpcli::install, vccw]
==> default: [2015-02-24T04:48:51+00:00] INFO: Starting Chef Run for kd00.local
==> default: [2015-02-24T04:48:51+00:00] INFO: Running start handlers
==> default: [2015-02-24T04:48:51+00:00] INFO: Start handlers complete.
==> default: [2015-02-24T04:48:51+00:00] ERROR: Running exception handlers
==> default: [2015-02-24T04:48:51+00:00] ERROR: Exception handlers complete
==> default: [2015-02-24T04:48:51+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-02-24T04:48:51+00:00] ERROR: Cookbook yum not found. If you're loading yum from another cookbook, make sure you configure the dependency in your metadata
==> default: [2015-02-24T04:48:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

any help?

Thank you

**Comment by miya0001** [comment]
Can you provision with default vccw?

**Comment by bobhattori** [comment]
Yes. actually i can.
I was installing vccw in custom directory, instead of using "vccw-2.4.0" folder, and it didn't work right.
So I reinstall it with folder, and it's all right now.
My directory is now like this
hoge¥vccc-2.4.0¥vagrantfile...etc
My current directory was like this
hoge¥vagrantfile...etc
perhaps this might be the reason?
I'm not familiar with vagrant, so if I'm doing wrong, please let me know.

Sorry to bother you.

Thank you.

**Comment by miya0001** [comment]
Please run command `vagrant global-status`, and please halt or destroy another vagrant machines.
Then please provision vccw.
