### ISSUE TITLE
Chef never successfully completed! error is occured

### ISSUE THREAD

**Issue by ryohei0411** [vccw-team/vccw#76]
Hello
my environment is
・Mac OS X Yosemite v10.10.3
・Vagrant 1.7.2
・VirtualBox 4.3.26
・VCCW v2.11.0

I runned 'vagrant up' the error below occured.

>Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

I tried some other versions VCCW but all of them didn't work.

Help me, please!

**Comment by miya0001** [comment]
Please share error message.
I don't have supernatural power. :wink:

**Comment by ryohei0411** [comment]
I'm sorry for forgetting to share code.
Below is the err message.

```
==> default: Running chef-solo...
==> default: [2015-06-18T05:24:39+00:00] INFO: Forking chef instance to converge...
==> default: [2015-06-18T05:24:39+00:00] WARN: 
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> default: encrypted, but chef is not able to detect forged replies or man in the middle
==> default: attacks.
==> default: 
==> default: To fix this issue add an entry like this to your configuration file:
==> default: 
==> default: ```
==> default:   # Verify all HTTPS connections (recommended)
==> default:   ssl_verify_mode :verify_peer
==> default: 
==> default:   # OR, Verify only connections to chef-server
==> default:   verify_api_cert true
==> default: ```
==> default: 
==> default: To check your SSL configuration, or troubleshoot errors, you can use the
==> default: `knife ssl check` command like so:
==> default: 
==> default: ```
==> default:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> default: ```
==> default: 
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: [2015-06-18T05:24:39+00:00] INFO: *** Chef 11.16.4 ***
==> default: [2015-06-18T05:24:39+00:00] INFO: Chef-client pid: 20231
==> default: [2015-06-18T05:24:56+00:00] INFO: Setting the run_list to ["recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> default: [2015-06-18T05:24:56+00:00] INFO: Run List is [recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> default: [2015-06-18T05:24:56+00:00] INFO: Run List expands to [wpcli, wpcli::install, vccw]
==> default: [2015-06-18T05:24:56+00:00] INFO: Starting Chef Run for wordpress.local
==> default: [2015-06-18T05:24:56+00:00] INFO: Running start handlers
==> default: [2015-06-18T05:24:56+00:00] INFO: Start handlers complete.
==> default: [2015-06-18T05:24:56+00:00] ERROR: Running exception handlers
==> default: [2015-06-18T05:24:56+00:00] ERROR: Exception handlers complete
==> default: [2015-06-18T05:24:56+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-06-18T05:24:56+00:00] ERROR: Cookbook wpcli not found. If you're loading wpcli from another cookbook, make sure you configure the dependency in your metadata
==> default: [2015-06-18T05:24:56+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by miya0001** [comment]
Are there any vagrant machines in your local machine?
Please open VirtualBox.app.

If you have another machines, please shutdown all virtual machines.

**Comment by ryohei0411** [comment]
Due to your answer, vagrant successfully ran "vagrant up".
But I got the same message as the above when I tried "vagrant provision".

I confirmed only 1 local machine working in GUI of VirtualBox.app and  ```VBoxManage list vms``` and ```vagrant global-status```.

**Comment by miya0001** [comment]
Sorry for late.

Please try with latest version of VirtualBox and Vagrant.
Because it looks problem with shared folder.

**Comment by ryohei0411** [comment]
Thank you for reply.
Finally I achieved my goal after so many trial and error that I can't explain it all...
At least I installed chef, latest ruby, and latest mysql with Homebrew. Then anything works well.
I don't know what's happened...

Anyway, I appreciate to your help.

**Comment by adamclerk** [comment]
I'm now running into the same issue. Is there a proposed resolution?

**Comment by ryohei0411** [comment]
In my case,  I reinstalled chef, latest ruby, and latest mysql with Homebrew.
And confirm that latest version of VB and Vagrant is installed.

**Comment by miya0001** [comment]
You don't need chef in your system for VCCW, It runs only in virtual machine.
And also Vagrant includes ruby too. :)

**Comment by MarkehMe** [comment]
I have just run into this issue myself..


```
$ vagrant provision
==> vccw.dev: Running provisioner: chef_solo...
==> vccw.dev: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> vccw.dev: Running chef-solo...
==> vccw.dev: [2015-11-27T06:39:43+00:00] INFO: Forking chef instance to converge...
==> vccw.dev: [2015-11-27T06:39:43+00:00] WARN: 
==> vccw.dev: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> vccw.dev: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> vccw.dev: encrypted, but chef is not able to detect forged replies or man in the middle
==> vccw.dev: attacks.
==> vccw.dev: 
==> vccw.dev: To fix this issue add an entry like this to your configuration file:
==> vccw.dev: 
==> vccw.dev: ```
==> vccw.dev:   # Verify all HTTPS connections (recommended)
==> vccw.dev:   ssl_verify_mode :verify_peer
==> vccw.dev: 
==> vccw.dev:   # OR, Verify only connections to chef-server
==> vccw.dev:   verify_api_cert true
==> vccw.dev: ```
==> vccw.dev: 
==> vccw.dev: To check your SSL configuration, or troubleshoot errors, you can use the
==> vccw.dev: `knife ssl check` command like so:
==> vccw.dev: 
==> vccw.dev: ```
==> vccw.dev:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> vccw.dev: ```
==> vccw.dev: 
==> vccw.dev: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> vccw.dev: Starting Chef Client, version 11.16.4
==> vccw.dev: [2015-11-27T06:39:43+00:00] INFO: *** Chef 11.16.4 ***
==> vccw.dev: [2015-11-27T06:39:43+00:00] INFO: Chef-client pid: 28059
==> vccw.dev: [2015-11-27T06:39:48+00:00] INFO: Setting the run_list to ["recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> vccw.dev: [2015-11-27T06:39:48+00:00] INFO: Run List is [recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> vccw.dev: [2015-11-27T06:39:48+00:00] INFO: Run List expands to [wpcli, wpcli::install, vccw]
==> vccw.dev: [2015-11-27T06:39:48+00:00] INFO: Starting Chef Run for vccw.dev
==> vccw.dev: [2015-11-27T06:39:48+00:00] INFO: Running start handlers
==> vccw.dev: [2015-11-27T06:39:48+00:00] INFO: Start handlers complete.
==> vccw.dev: Compiling Cookbooks...
==> vccw.dev: 
==> vccw.dev: Running handlers:
==> vccw.dev: [2015-11-27T06:39:48+00:00] ERROR: Running exception handlers
==> vccw.dev: Running handlers complete
==> vccw.dev: 
==> vccw.dev: [2015-11-27T06:39:48+00:00] ERROR: Exception handlers complete
==> vccw.dev: [2015-11-27T06:39:48+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> vccw.dev: Chef Client failed. 0 resources updated in 5.107558522 seconds
==> vccw.dev: [2015-11-27T06:39:48+00:00] ERROR: Cookbook wpcli not found. If you're loading wpcli from another cookbook, make sure you configure the dependency in your metadata
==> vccw.dev: [2015-11-27T06:39:48+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

```

(/var/chef/cache/chef-stacktrace.out does not exist)

**Comment by miya0001** [comment]
it seems like a problem of shared folder with your host machine and virtual machine.
Are your Vagrant and VirtualBox latest?

**Comment by MarkehMe** [comment]
Yep. Solved the issue by a fresh install though, unfortunately did not have time to debug the issue for you. 

It was the shared folder, checked myself. Not sure why it wasn't doing it though.

**Comment by linwoodc3** [comment]
Chef error in vagrant
OS = OSX El Capitan, 10.11.3

No one is putting down a solution.  I'm running vagrant 1.8.1 and getting the:

Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

Can someone please write down what they did to solve the problem?!?!  Please.  Sad everyone is experiencing the same thing.

**Comment by okonomiyaki3000** [comment]
I'm getting something similar but maybe a little different. Sorry, it's pretty long:

```
==> vccw.dev: Running chef-solo...
==> vccw.dev: [2016-03-31T15:31:05+00:00] INFO: Forking chef instance to converge...
==> vccw.dev: [2016-03-31T15:31:05+00:00] WARN:
==> vccw.dev: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> vccw.dev: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> vccw.dev: encrypted, but chef is not able to detect forged replies or man in the middle
==> vccw.dev: attacks.
==> vccw.dev:
==> vccw.dev: To fix this issue add an entry like this to your configuration file:
==> vccw.dev:
==> vccw.dev: ```
==> vccw.dev:   # Verify all HTTPS connections (recommended)
==> vccw.dev:   ssl_verify_mode :verify_peer
==> vccw.dev:
==> vccw.dev:   # OR, Verify only connections to chef-server
==> vccw.dev:   verify_api_cert true
==> vccw.dev: ```
==> vccw.dev:
==> vccw.dev: To check your SSL configuration, or troubleshoot errors, you can use the
==> vccw.dev: `knife ssl check` command like so:
==> vccw.dev:
==> vccw.dev: ```
==> vccw.dev:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> vccw.dev: ```
==> vccw.dev:
==> vccw.dev: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> vccw.dev: Starting Chef Client, version 11.16.4
==> vccw.dev: [2016-03-31T15:31:05+00:00] INFO: *** Chef 11.16.4 ***
==> vccw.dev: [2016-03-31T15:31:05+00:00] INFO: Chef-client pid: 27089
==> vccw.dev: [2016-03-31T15:31:06+00:00] INFO: Setting the run_list to ["recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> vccw.dev: [2016-03-31T15:31:06+00:00] INFO: Run List is [recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> vccw.dev: [2016-03-31T15:31:06+00:00] INFO: Run List expands to [wpcli, wpcli::install, vccw]
==> vccw.dev: [2016-03-31T15:31:06+00:00] INFO: Starting Chef Run for vagrant-daa6ca8a
==> vccw.dev: [2016-03-31T15:31:06+00:00] INFO: Running start handlers
==> vccw.dev: [2016-03-31T15:31:06+00:00] INFO: Start handlers complete.
==> vccw.dev: Compiling Cookbooks...
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Cloning resource attributes for package[perl] from prior resource (CHEF-3694)
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Previous package[perl]: /tmp/vagrant-chef/e3ade6ffc86d2c17aa3f204caebfef5c/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Current  package[perl]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/default.rb:51:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Cloning resource attributes for service[apache2] from prior resource (CHEF-3694)
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Previous service[apache2]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/default.rb:24:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Current  service[apache2]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/default.rb:221:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Cloning resource attributes for file[/etc/httpd/conf.d/ssl.conf] from prior resource (CHEF-3694)
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Previous file[/etc/httpd/conf.d/ssl.conf]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/default.rb:84:in `block in from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Current  file[/etc/httpd/conf.d/ssl.conf]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/mod_ssl.rb:31:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Cloning resource attributes for template[/etc/httpd/ports.conf] from prior resource (CHEF-3694)
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Previous template[/etc/httpd/ports.conf]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/default.rb:195:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Current  template[/etc/httpd/ports.conf]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/apache2/recipes/mod_ssl.rb:37:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Cloning resource attributes for directory[/var/lib/mysql] from prior resource (CHEF-3694)
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Previous directory[/var/lib/mysql]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/mysql/recipes/server.rb:108:in `block in from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Current  directory[/var/lib/mysql]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/mysql/recipes/server.rb:108:in `block in from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] INFO: Could not find previously defined grants.sql resource
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Cloning resource attributes for service[mysql] from prior resource (CHEF-3694)
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Previous service[mysql]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/mysql/recipes/server.rb:154:in `from_file'
==> vccw.dev: [2016-03-31T15:31:07+00:00] WARN: Current  service[mysql]: /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/mysql/recipes/server.rb:218:in `from_file'
==> vccw.dev: Recipe: build-essential::rhel
==> vccw.dev:
==> vccw.dev: * package[autoconf] action install
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:
==> vccw.dev: ================================================================================
==> vccw.dev:
==> vccw.dev: Error executing action `install` on resource 'package[autoconf]'
==> vccw.dev:
==> vccw.dev: ================================================================================
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:     Mixlib::ShellOut::ShellCommandFailed
==> vccw.dev:     ------------------------------------
==> vccw.dev:     Expected process to exit with [0], but received '1'
==> vccw.dev:     ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev:     STDOUT: [option installonlypkgs] kernel kernel-bigmem installonlypkg(kernel-module) installonlypkg(vm) kernel-enterprise kernel-smp kernel-debug kernel-unsupported kernel-source kernel-devel kernel-PAE kernel-PAE-debug
==> vccw.dev:     Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock error was
==> vccw.dev:     14: PYCURL ERROR 7 - "Failed to connect to 0.0.7.29: Invalid argument"
==> vccw.dev:     STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: base
==> vccw.dev:     ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev:     Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
==> vccw.dev:
==> vccw.dev:     Cookbook Trace:
==> vccw.dev:     ---------------
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:41:in `block in from_file'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:36:in `each'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:36:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/mysql/recipes/ruby.rb:24:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/e3ade6ffc86d2c17aa3f204caebfef5c/cookbooks/wpcli/recipes/install.rb:10:in `from_file'
==> vccw.dev:
==> vccw.dev:     Resource Declaration:
==> vccw.dev:     ---------------------
==> vccw.dev:     # In /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb
==> vccw.dev:
==> vccw.dev:      38:   r = package pkg do
==> vccw.dev:      39:     action( node['build_essential']['compiletime'] ? :nothing : :install )
==> vccw.dev:      40:   end
==> vccw.dev:      41:   r.run_action(:install) if node['build_essential']['compiletime']
==> vccw.dev:
==> vccw.dev:     Compiled Resource:
==> vccw.dev:     ------------------
==> vccw.dev:     # Declared in /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:38:in `block in from_file'
==> vccw.dev:
==> vccw.dev:     package("autoconf") do
==> vccw.dev:       action [:nothing]
==> vccw.dev:       retries 0
==> vccw.dev:       retry_delay 2
==> vccw.dev:       guard_interpreter :default
==> vccw.dev:       package_name "autoconf"
==> vccw.dev:       timeout 900
==> vccw.dev:       cookbook_name :"build-essential"
==> vccw.dev:       recipe_name "rhel"
==> vccw.dev:     end
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:
==> vccw.dev: ================================================================================
==> vccw.dev:
==> vccw.dev: Recipe Compile Error in /tmp/vagrant-chef/e3ade6ffc86d2c17aa3f204caebfef5c/cookbooks/wpcli/recipes/install.rb
==> vccw.dev:
==> vccw.dev: ================================================================================
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:   Mixlib::ShellOut::ShellCommandFailed
==> vccw.dev:   ------------------------------------
==> vccw.dev:   package[autoconf] (build-essential::rhel line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> vccw.dev:   ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev:   STDOUT: [option installonlypkgs] kernel kernel-bigmem installonlypkg(kernel-module) installonlypkg(vm) kernel-enterprise kernel-smp kernel-debug kernel-unsupported kernel-source kernel-devel kernel-PAE kernel-PAE-debug
==> vccw.dev:   Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock error was
==> vccw.dev:   14: PYCURL ERROR 7 - "Failed to connect to 0.0.7.29: Invalid argument"
==> vccw.dev:   STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: base
==> vccw.dev:   ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev:   Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
==> vccw.dev:
==> vccw.dev:   Cookbook Trace:
==> vccw.dev:   ---------------
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:41:in `block in from_file'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:36:in `each'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:36:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/mysql/recipes/ruby.rb:24:in `from_file'
==> vccw.dev:     /tmp/vagrant-chef/e3ade6ffc86d2c17aa3f204caebfef5c/cookbooks/wpcli/recipes/install.rb:10:in `from_file'
==> vccw.dev:
==> vccw.dev:   Relevant File Content:
==> vccw.dev:   ----------------------
==> vccw.dev:   /tmp/vagrant-chef/3841741cc0484b5f1b7809d9680e6183/cookbooks/build-essential/recipes/rhel.rb:
==> vccw.dev:
==> vccw.dev:    34:  end
==> vccw.dev:    35:
==> vccw.dev:    36:  pkgs.flatten.each do |pkg|
==> vccw.dev:    37:
==> vccw.dev:    38:    r = package pkg do
==> vccw.dev:    39:      action( node['build_essential']['compiletime'] ? :nothing : :install )
==> vccw.dev:    40:    end
==> vccw.dev:    41>>   r.run_action(:install) if node['build_essential']['compiletime']
==> vccw.dev:    42:
==> vccw.dev:    43:  end
==> vccw.dev:    44:
==> vccw.dev:
==> vccw.dev:
==> vccw.dev:   Running handlers:
==> vccw.dev: [2016-03-31T15:31:07+00:00] ERROR: Running exception handlers
==> vccw.dev:   Running handlers complete
==> vccw.dev: [2016-03-31T15:31:07+00:00] ERROR: Exception handlers complete
==> vccw.dev: [2016-03-31T15:31:07+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> vccw.dev:
==> vccw.dev: Chef Client failed. 0 resources updated in 2.494322281 seconds
==> vccw.dev: [2016-03-31T15:31:07+00:00] ERROR: package[autoconf] (build-essential::rhel line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> vccw.dev: ---- Begin output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: STDOUT: [option installonlypkgs] kernel kernel-bigmem installonlypkg(kernel-module) installonlypkg(vm) kernel-enterprise kernel-smp kernel-debug kernel-unsupported kernel-source kernel-devel kernel-PAE kernel-PAE-debug
==> vccw.dev: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=i386&repo=os&infra=stock error was
==> vccw.dev: 14: PYCURL ERROR 7 - "Failed to connect to 0.0.7.29: Invalid argument"
==> vccw.dev: STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: base
==> vccw.dev: ---- End output of /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
==> vccw.dev: Ran /usr/bin/python /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1
==> vccw.dev: [2016-03-31T15:31:07+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by okonomiyaki3000** [comment]
Ah, in case it's relevant, I'm on OSX 10.11.4, vagrant 1.8.1, virtualbox 5.0.16 r105871, vccw 2.19.0

**Comment by miya0001** [comment]
There is a following line in your error.
```
"Failed to connect to 0.0.7.29: Invalid argument"
```
I guess it is a temporary failure.

If you would have a error while vagrant is provisioning.
Please try `vagrant provision`.

**Comment by okonomiyaki3000** [comment]
I've tried that many times. Always the same thing. I've also tried switching it off and switching it back on again.

**Comment by miya0001** [comment]
OK, thanks.

Are there any machines in VirtualBox app?
If you have another machines, please stop them.
Then try again.

**Comment by okonomiyaki3000** [comment]
There are machines but they are not active. Should I delete them completely?

**Comment by miya0001** [comment]
I guess you don't need to delete, but If you don't need those machines you should delete them.
(You can save disk. 😄 )

**Comment by okonomiyaki3000** [comment]
Well that's a good tip but it's not really my immediate problem.

**Comment by okonomiyaki3000** [comment]
I figured it out. During the provisioning process, I suppose there are some connections made to github using ssh. These will fail if the user has not registered a public key with github (which I had not). Maybe this prerequisite should be added to the instructions page. I don't know if it's the same problem that @MarkehMe and @ryohei0411 were having but it does look very similar.

**Comment by miya0001** [comment]
Nice! If you have time I want you to try following for investigating details. 😄 

## Disable forward_agent

https://github.com/vccw-team/vccw/blob/master/Vagrantfile#L52

Before:
```
  config.ssh.forward_agent = true
```

After:
```
  config.ssh.forward_agent = false
```

## Provision

Then:
```
vagrant up
```

**Comment by okonomiyaki3000** [comment]
Should I try that with or without my key registered at github? Since I've registered it now, `vagrant up` seems to work properly and the box is up and running.

**Comment by miya0001** [comment]
I wanted you to try with not-registerd key, but you already registered, so I will try it.
Thanks! I learned many things. 😄

**Comment by okonomiyaki3000** [comment]
Glad I could help!

**Comment by HengYk** [comment]
#228
