### ISSUE TITLE
プロビジョニングでWP_CLIがエラーとなっています

### ISSUE THREAD

**Issue by kazoo0217** [vccw-team/vccw#77]
こんばんは、日本語で失礼いたします。

- Windows7 Pro 64Bit
- VirtualBox 4.3.26
- Vagrant 1.7.2
- VCCW v2.11.0

```
> vagrant up
```

を実行し、以下のメッセージで終了していたのですが、ブラウザーでサイトを表示しても404となり、WPが表示されません。

```
==> mydomain.jp.local: STDERR: PHP Fatal error:  Call to undefined function WP_CLI\wp_clean_update_cache() in phar:///usr/share/wp-cli/phar/wp-cli.phar/php/WP_CLI/CommandWithTranslation.php on line 162
==> mydomain.jp.local: Fatal error: Call to undefined function WP_CLI\wp_clean_update_cache() in phar:///usr/share/wp-cli/phar/wp-cli.phar/php/WP_CLI/CommandWithTranslation.php on line 162
==> mydomain.jp.local: ---- End output of "bash"  "/tmp/chef-script20150626-26705-1qtjztr" ----
==> mydomain.jp.local: Ran "bash"  "/tmp/chef-script20150626-26705-1qtjztr" returned 255
==> mydomain.jp.local: [2015-06-26T10:28:46+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the output above. Please fix your recipes so that they properly complete.
```

WP_CLIがエラーを出しているようで、どういった状態か分からないのですが、Provisioningが完全に完了していないようです。
通常ならMovefileが作成されるのですが、作成されていませんでした。

数日前、同環境で別のローカルサイトを作成した時には問題は無かったです。
WP_CLIの問題かもしれませんが、ご確認いただけますでしょうか。

よろしくお願い申し上げます。

**Comment by miya0001** [comment]
ネットワークなどの問題により一時的にエラーが発生することがありますので、その場合は`vagrant provision`を行うと多くの場合問題が解決します。
それでも問題が発生する場合は、`vagrant destroy`してから`vagrant up`してください。

それでもなお問題が発生する場合はVagrant及びVirtualBox、Vagrantのプラグインを最新版にしてください。

**Comment by kazoo0217** [comment]
こんにちは。  
お返事ありがとうございます。

何度か`vagrant destroy`を繰り返してみましたが、同様の症状になっています。  
別の環境でも試してみましたが、同じくエラーとなりました。

- MacOS 10.9.5
- VirtualBox 4.3.26
- Vagrant 1.7.2
- VCCW v2.11.0
- VagrantBox 2.8.2
- vagrant-hostsupdater 0.0.11
- vagrant-share 1.1.3, system

以下全てのログになります。

```
user-no-MacBook-Pro:mydomain.local user$ vagrant up
Bringing machine 'mydomain.local' up with 'virtualbox' provider...
==> mydomain.local: Importing base box 'miya0001/vccw'...
==> mydomain.local: Matching MAC address for NAT networking...
==> mydomain.local: Checking if box 'miya0001/vccw' is up to date...
==> mydomain.local: Setting the name of the VM: mydomain.local
==> mydomain.local: Clearing any previously set network interfaces...
==> mydomain.local: Preparing network interfaces based on configuration...
    mydomain.local: Adapter 1: nat
    mydomain.local: Adapter 2: hostonly
==> mydomain.local: Forwarding ports...
    mydomain.local: 22 => 2222 (adapter 1)
==> mydomain.local: Running 'pre-boot' VM customizations...
==> mydomain.local: Booting VM...
==> mydomain.local: Waiting for machine to boot. This may take a few minutes...
    mydomain.local: SSH address: 127.0.0.1:2222
    mydomain.local: SSH username: vagrant
    mydomain.local: SSH auth method: private key
    mydomain.local: Warning: Connection timeout. Retrying...
    mydomain.local:
    mydomain.local: Vagrant insecure key detected. Vagrant will automatically replace
    mydomain.local: this with a newly generated keypair for better security.
    mydomain.local:
    mydomain.local: Inserting generated public key within guest...
    mydomain.local: Removing insecure key from the guest if its present...
    mydomain.local: Key inserted! Disconnecting and reconnecting using new SSH key...
==> mydomain.local: Machine booted and ready!
==> mydomain.local: Checking for guest additions in VM...
==> mydomain.local: Checking for host entries
==> mydomain.local: adding to (/etc/hosts) : 192.168.33.10  mydomain.local  # VAGRANT: bc75a7da271ad78a4b6819f06096b002 (mydomain.local) / d0e86418-3b2d-4192-a5a4-26526b3f4d58
==> mydomain.local: Setting hostname...
==> mydomain.local: Configuring and enabling network interfaces...
^@==> mydomain.local: Mounting shared folders...
    mydomain.local: /vagrant => /Users/user/Desktop/mydomain.local
    mydomain.local: /var/www/html => /Users/user/Desktop/mydomain.local
    mydomain.local: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks => /Users/user/Desktop/mydomain.local/provision/cookbooks
    mydomain.local: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks => /Users/user/Desktop/mydomain.local/provision/site-cookbooks
==> mydomain.local: Running provisioner: chef_solo...
==> mydomain.local: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> mydomain.local: Running chef-solo...
==> mydomain.local: [2015-06-27T05:19:55+00:00] INFO: Forking chef instance to converge...
==> mydomain.local: [2015-06-27T05:19:55+00:00] WARN:
==> mydomain.local: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> mydomain.local: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> mydomain.local: encrypted, but chef is not able to detect forged replies or man in the middle
==> mydomain.local: attacks.
==> mydomain.local:
==> mydomain.local: To fix this issue add an entry like this to your configuration file:
==> mydomain.local:
==> mydomain.local: ```
==> mydomain.local:   # Verify all HTTPS connections (recommended)
==> mydomain.local:   ssl_verify_mode :verify_peer
==> mydomain.local:
==> mydomain.local:   # OR, Verify only connections to chef-server
==> mydomain.local:   verify_api_cert true
==> mydomain.local: ```
==> mydomain.local:
==> mydomain.local: To check your SSL configuration, or troubleshoot errors, you can use the
==> mydomain.local: `knife ssl check` command like so:
==> mydomain.local:
==> mydomain.local: ```
==> mydomain.local:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> mydomain.local: ```
==> mydomain.local:
==> mydomain.local: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> mydomain.local:
==> mydomain.local: [2015-06-27T05:19:55+00:00] INFO: *** Chef 11.16.4 ***
==> mydomain.local: [2015-06-27T05:19:55+00:00] INFO: Chef-client pid: 26654
^@==> mydomain.local: [2015-06-27T05:20:12+00:00] INFO: Setting the run_list to ["recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
==> mydomain.local: [2015-06-27T05:20:12+00:00] INFO: Run List is [recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
==> mydomain.local: [2015-06-27T05:20:12+00:00] INFO: Run List expands to [wpcli, wpcli::install, vccw]
==> mydomain.local: [2015-06-27T05:20:12+00:00] INFO: Starting Chef Run for mydomain.local
==> mydomain.local: [2015-06-27T05:20:12+00:00] INFO: Running start handlers
==> mydomain.local: [2015-06-27T05:20:12+00:00] INFO: Start handlers complete.
==> mydomain.local: [2015-06-27T05:20:12+00:00] WARN: Cloning resource attributes for package[perl] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:20:12+00:00] WARN: Previous package[perl]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> mydomain.local: [2015-06-27T05:20:12+00:00] WARN: Current  package[perl]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/default.rb:51:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Cloning resource attributes for service[apache2] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Previous service[apache2]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/default.rb:24:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Current  service[apache2]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/default.rb:221:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Cloning resource attributes for file[/etc/httpd/conf.d/ssl.conf] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Previous file[/etc/httpd/conf.d/ssl.conf]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/default.rb:84:in `block in from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Current  file[/etc/httpd/conf.d/ssl.conf]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/mod_ssl.rb:31:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Cloning resource attributes for template[/etc/httpd/ports.conf] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Previous template[/etc/httpd/ports.conf]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/default.rb:195:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Current  template[/etc/httpd/ports.conf]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/apache2/recipes/mod_ssl.rb:37:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Cloning resource attributes for directory[/var/lib/mysql] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Previous directory[/var/lib/mysql]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/mysql/recipes/server.rb:108:in `block in from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Current  directory[/var/lib/mysql]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/mysql/recipes/server.rb:108:in `block in from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] INFO: Could not find previously defined grants.sql resource
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Cloning resource attributes for service[mysql] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Previous service[mysql]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/mysql/recipes/server.rb:154:in `from_file'
==> mydomain.local: [2015-06-27T05:20:13+00:00] WARN: Current  service[mysql]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/mysql/recipes/server.rb:218:in `from_file'
^@==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Cloning resource attributes for package[gcc] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Previous package[gcc]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Current  package[gcc]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/build-essential/recipes/rhel.rb:38:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Cloning resource attributes for package[kernel-devel] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Previous package[kernel-devel]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Current  package[kernel-devel]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/build-essential/recipes/rhel.rb:38:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Cloning resource attributes for package[make] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Previous package[make]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Current  package[make]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/build-essential/recipes/rhel.rb:38:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Cloning resource attributes for package[git] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Previous package[git]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:07+00:00] WARN: Current  package[git]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/ruby_build/recipes/default.rb:38:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:08+00:00] WARN: Cloning resource attributes for package[subversion] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:21:08+00:00] WARN: Previous package[subversion]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/default.rb:12:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:08+00:00] WARN: Current  package[subversion]: /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/vccw/recipes/default.rb:13:in `block in from_file'
==> mydomain.local: [2015-06-27T05:21:08+00:00] INFO: Adding and updating remi repository in /etc/yum.repos.d/remi.repo
==> mydomain.local: [2015-06-27T05:21:08+00:00] WARN: Cloning resource attributes for yum_key[RPM-GPG-KEY-remi] from prior resource (CHEF-3694)
==> mydomain.local: [2015-06-27T05:21:08+00:00] WARN: Previous yum_key[RPM-GPG-KEY-remi]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/yum/recipes/remi.rb:22:in `from_file'
==> mydomain.local: [2015-06-27T05:21:08+00:00] WARN: Current  yum_key[RPM-GPG-KEY-remi]: /tmp/vagrant-chef/02fa30cf1f31d2a4419a79a3fd016930/cookbooks/yum/providers/repository.rb:85:in `repo_config'
==> mydomain.local: [2015-06-27T05:21:08+00:00] INFO: template[/etc/yum.repos.d/remi.repo] backed up to /var/chef/backup/etc/yum.repos.d/remi.repo.chef-20150627052108.196940
==> mydomain.local: [2015-06-27T05:21:08+00:00] INFO: template[/etc/yum.repos.d/remi.repo] updated file contents /etc/yum.repos.d/remi.repo
==> mydomain.local: [2015-06-27T05:21:08+00:00] INFO: template[/etc/yum.repos.d/remi.repo] sending run action to execute[yum-makecache] (immediate)
^@^@^@==> mydomain.local: [2015-06-27T05:24:16+00:00] INFO: execute[yum-makecache] ran successfully
==> mydomain.local: [2015-06-27T05:24:16+00:00] INFO: template[/etc/yum.repos.d/remi.repo] sending create action to ruby_block[reload-internal-yum-cache] (immediate)
==> mydomain.local: [2015-06-27T05:24:16+00:00] INFO: ruby_block[reload-internal-yum-cache] called
==> mydomain.local: [2015-06-27T05:24:19+00:00] INFO: package[kernel-devel] installing kernel-devel-2.6.32-504.23.4.el6 from updates repository
==> mydomain.local: [2015-06-27T05:24:58+00:00] INFO: package[kernel-devel] upgraded from 2.6.32-504.16.2.el6 to 2.6.32-504.23.4.el6
^@==> mydomain.local: [2015-06-27T05:25:08+00:00] INFO: git[/usr/share/wp-cli] updated to revision 14b67edd9b517ae1406cfd8be2796eb2012c6fa1
==> mydomain.local: [2015-06-27T05:25:08+00:00] INFO: template[/home/vagrant/.wp-cli/config.yml] backed up to /var/chef/backup/home/vagrant/.wp-cli/config.yml.chef-20150627052508.781054
==> mydomain.local: [2015-06-27T05:25:08+00:00] INFO: template[/home/vagrant/.wp-cli/config.yml] updated file contents /home/vagrant/.wp-cli/config.yml
==> mydomain.local: [2015-06-27T05:25:10+00:00] INFO: template[/etc/httpd/sites-available/default] backed up to /var/chef/backup/etc/httpd/sites-available/default.chef-20150627052510.450728
==> mydomain.local: [2015-06-27T05:25:10+00:00] INFO: template[/etc/httpd/sites-available/default] updated file contents /etc/httpd/sites-available/default
==> mydomain.local: [2015-06-27T05:25:10+00:00] INFO: file[/etc/httpd/conf.d/php.conf] deleted file at /etc/httpd/conf.d/php.conf
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: template[/etc/mysql_grants.sql] backed up to /var/chef/backup/etc/mysql_grants.sql.chef-20150627052511.010545
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: template[/etc/mysql_grants.sql] updated file contents /etc/mysql_grants.sql
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: template[/etc/mysql_grants.sql] sending run action to execute[mysql-install-privileges] (immediate)
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: execute[mysql-install-privileges] ran successfully
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: template[/etc/my.cnf] backed up to /var/chef/backup/etc/my.cnf.chef-20150627052511.220585
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: template[/etc/my.cnf] updated file contents /etc/my.cnf
==> mydomain.local: [2015-06-27T05:25:11+00:00] INFO: template[/etc/my.cnf] sending restart action to service[mysql] (immediate)
==> mydomain.local: [2015-06-27T05:25:14+00:00] INFO: service[mysql] restarted
==> mydomain.local: [2015-06-27T05:25:15+00:00] INFO: template[/etc/wp-grants.sql] backed up to /var/chef/backup/etc/wp-grants.sql.chef-20150627052515.065913
==> mydomain.local: [2015-06-27T05:25:15+00:00] INFO: template[/etc/wp-grants.sql] updated file contents /etc/wp-grants.sql
==> mydomain.local: [2015-06-27T05:25:15+00:00] INFO: template[/etc/wp-grants.sql] sending run action to execute[mysql-install-wp-privileges] (immediate)
==> mydomain.local: [2015-06-27T05:25:15+00:00] INFO: execute[mysql-install-wp-privileges] ran successfully
==> mydomain.local: [2015-06-27T05:25:32+00:00] INFO: bash[wordpress-core-download] ran successfully
==> mydomain.local: [2015-06-27T05:25:33+00:00] INFO: bash[wordpress-core-config] ran successfully
==> mydomain.local: [2015-06-27T05:25:33+00:00] INFO: bash[wordpress-db-reset] ran successfully
==> mydomain.local: [2015-06-27T05:25:35+00:00] INFO: bash[wordpress-core-install] ran successfully
==> mydomain.local: [2015-06-27T05:25:35+00:00] INFO: bash[wordpress-plugin-ja-install] ran successfully
==> mydomain.local:
==> mydomain.local:
==> mydomain.local: ================================================================================
==> mydomain.local: Error executing action `run` on resource 'bash[WordPress dynamic-hostname install]'
==> mydomain.local: ================================================================================
==> mydomain.local:
==> mydomain.local: Mixlib::ShellOut::ShellCommandFailed
==> mydomain.local: ------------------------------------
==> mydomain.local: Expected process to exit with [0], but received '255'
==> mydomain.local: ---- Begin output of "bash"  "/tmp/chef-script20150627-26654-2o5txl" ----
==> mydomain.local: STDOUT: Installing Dynamic Hostname (0.4.2)
==> mydomain.local: https://downloads.wordpress.org/plugin/dynamic-hostname.0.4.2.zip からインストールパッケージをダウンロードしています…
==> mydomain.local: パッケージを展開しています…
==> mydomain.local: プラグインをインストールしています…
==> mydomain.local: プラグインのインストールが完了しました。
==> mydomain.local: STDERR: PHP Fatal error:  Call to undefined function WP_CLI\wp_clean_update_cache() in phar:///usr/share/wp-cli/phar/wp-cli.phar/php/WP_CLI/CommandWithTranslation.php on line 162
==> mydomain.local: Fatal error: Call to undefined function WP_CLI\wp_clean_update_cache() in phar:///usr/share/wp-cli/phar/wp-cli.phar/php/WP_CLI/CommandWithTranslation.php on line 162
==> mydomain.local: ---- End output of "bash"  "/tmp/chef-script20150627-26654-2o5txl" ----
==> mydomain.local: Ran "bash"  "/tmp/chef-script20150627-26654-2o5txl" returned 255
==> mydomain.local:
==> mydomain.local: Resource Declaration:
==> mydomain.local: ---------------------
==> mydomain.local: # In /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/install.rb
==> mydomain.local:
==> mydomain.local: 170:   bash "WordPress #{plugin} install" do
==> mydomain.local: 171:     user node[:wpcli][:user]
==> mydomain.local: 172:     group node[:wpcli][:group]
==> mydomain.local: 173:     cwd File.join(node[:wpcli][:wp_docroot], node[:wpcli][:wp_siteurl])
==> mydomain.local: 174:     code "WP_CLI_CONFIG_PATH=#{Shellwords.shellescape(node[:wpcli][:config_path])} wp plugin install #{Shellwords.shellescape(plugin)} --activate"
==> mydomain.local: 175:   end
==> mydomain.local: 176: end
==> mydomain.local:
==> mydomain.local: Compiled Resource:
==> mydomain.local: ------------------
==> mydomain.local: # Declared in /tmp/vagrant-chef/233f838930f12c3b08bb73869e7c2848/cookbooks/wpcli/recipes/install.rb:170:in `block in from_file'
==> mydomain.local:
==> mydomain.local: bash("WordPress dynamic-hostname install") do
==> mydomain.local:   action "run"
==> mydomain.local:   retries 0
==> mydomain.local:   retry_delay 2
==> mydomain.local:   guard_interpreter :default
==> mydomain.local:   command "\"bash\"  \"/tmp/chef-script20150627-26654-2o5txl\""
==> mydomain.local:   backup 5
==> mydomain.local:   cwd "/var/www/html/"
==> mydomain.local:   group "vagrant"
==> mydomain.local:   returns 0
==> mydomain.local:   user "vagrant"
==> mydomain.local:   code "WP_CLI_CONFIG_PATH=/home/vagrant/.wp-cli/config.yml wp plugin install dynamic-hostname --activate"
==> mydomain.local:   interpreter "bash"
==> mydomain.local:   cookbook_name :wpcli
==> mydomain.local:   recipe_name "install"
==> mydomain.local: end
==> mydomain.local:
==> mydomain.local: [2015-06-27T05:25:38+00:00] INFO: Running queued delayed notifications before re-raising exception
==> mydomain.local: [2015-06-27T05:25:38+00:00] INFO: template[/etc/httpd/sites-available/default] sending restart action to service[apache2] (delayed)
==> mydomain.local: [2015-06-27T05:25:39+00:00] INFO: service[apache2] restarted
==> mydomain.local: [2015-06-27T05:25:39+00:00] ERROR: Running exception handlers
==> mydomain.local: [2015-06-27T05:25:39+00:00] ERROR: Exception handlers complete
==> mydomain.local: [2015-06-27T05:25:39+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> mydomain.local: [2015-06-27T05:25:40+00:00] ERROR: bash[WordPress dynamic-hostname install] (wpcli::install line 170) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
==> mydomain.local: ---- Begin output of "bash"  "/tmp/chef-script20150627-26654-2o5txl" ----
==> mydomain.local: STDOUT: Installing Dynamic Hostname (0.4.2)
==> mydomain.local: https://downloads.wordpress.org/plugin/dynamic-hostname.0.4.2.zip からインストールパッケージをダウンロードしています…
==> mydomain.local: パッケージを展開しています…
==> mydomain.local: プラグインをインストールしています…
==> mydomain.local: プラグインのインストールが完了しました。
==> mydomain.local: STDERR: PHP Fatal error:  Call to undefined function WP_CLI\wp_clean_update_cache() in phar:///usr/share/wp-cli/phar/wp-cli.phar/php/WP_CLI/CommandWithTranslation.php on line 162
==> mydomain.local: Fatal error: Call to undefined function WP_CLI\wp_clean_update_cache() in phar:///usr/share/wp-cli/phar/wp-cli.phar/php/WP_CLI/CommandWithTranslation.php on line 162
==> mydomain.local: ---- End output of "bash"  "/tmp/chef-script20150627-26654-2o5txl" ----
==> mydomain.local: Ran "bash"  "/tmp/chef-script20150627-26654-2o5txl" returned 255
==> mydomain.local: [2015-06-27T05:25:40+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
ログの148行目とか、160行目とかのエラーが気になりますが、これで何か分かりますでしょうか？

よろしくお願い申し上げます。

**Comment by miya0001** [comment]
前述しましたがなお問題が発生する場合はVagrant及びVirtualBox、Vagrantのプラグインを最新版にしてください。

あと、`site.yml`はどうなっていますか？

**Comment by kazoo0217** [comment]
Vagrant、VirtualBox、Vagrantのpluginも最新版になっています。（前述の環境記述より新しいものがあるのでしょうか）

また色々と検証を繰り返しましたら、default.ymlの状態にすると、正常にprovisionが完了することが分かりまして、
wordpressのversionをlatestにしたところ、正常にprovisionが完了しました。エラーになったのは4.0に指定をしていました。

ymlの設定によってもこういったエラーになることもあるのですね。

とりあえず回避方法が分かりましたので、取り急ぎご報告まで。

お手数をお掛けいたしました。
ありがとうございます。



2015年6月27日 18:54 Takayuki Miyauchi <notifications@github.com>:

**Comment by miya0001** [comment]
確認したんですが、4.0にしても問題なくプロビジョニングできますね...
とりあえず解決したようなので閉じます。
